landing/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name="landing-page")
]

megaria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('landing.urls')),
    path('volunteers/', include('volunteers.urls'), name='volunteer')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

volunteers/urls.py
from django.urls import path
from .views import (
    PostListView, PostDetailView, PostEditView, PostDeleteView, CommentDeleteView, ProfileView, ProfileEditView, AddFollower, RemoveFollower, AddLike, AddDislike, UserSearch, ListFollowers, AddCommentLike, AddCommentDislike, CommentReplyView, PostNotification, FollowNotification, RemoveNotification, CreateThread, ListThreads, ThreadView, CreateThread, CreateMessage, ThreadNotification, SharedPostView, Explore, DonationListView, DonationDetailView)

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('explore/', Explore.as_view(), name='explore'),
    path('donation/', DonationListView.as_view(), name='donation-list'),
    path('donation/<int:pk>/', DonationDetailView.as_view(), name='donation-detail'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('post/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:post_pk>/comment/delete/<int:pk>/',
         CommentDeleteView.as_view(), name='comment-delete'),
    path('post/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name='comment-like'),
    path('post/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name='comment-dislike'),
    path('post/<int:post_pk>/comment/<int:pk>/reply', CommentReplyView.as_view(), name='comment-reply'),
    path('post/<int:pk>/like',AddLike.as_view(), name='like' ),
    path('post/<int:pk>/dislike',AddDislike.as_view(), name='dislike' ),
    path('post/<int:pk>/share', SharedPostView.as_view(), name='share-post'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/followers/', ListFollowers.as_view(), name='list-followers'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/add',
         AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove',
         RemoveFollower.as_view(), name='remove-follower'),
    path('search/', UserSearch.as_view(), name='profile-search'),
    path('notification/<int:notification_pk>/post/<int:post_pk>', PostNotification.as_view(), name='post-notification'),
    path('notification/<int:notification_pk>/profile/<int:profile_pk>', FollowNotification.as_view(), name='follow-notification'),
    path('notification/delete/<int:notification_pk>', RemoveNotification.as_view(), name='notification-delete'),
    path('notification/<int:notification_pk>/thread/<int:object_pk>', ThreadNotification.as_view(), name='thread-notification'),
    path('inbox/', ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread/', CreateThread.as_view(), name='create-thread'),
    path('inbox/<int:pk>/', ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', CreateMessage.as_view(), name='create-message'),





]

volunteers/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# from .location import getLocation
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
import time


class Post(models.Model):
    shared_body = models.TextField(blank=True, null=True)
    body = models.TextField()
    image = models.ManyToManyField('Image', blank=True)
    created_on = models.DateTimeField(default=timezone.now)
    shared_on = models.DateTimeField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    shared_user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True, related_name='+')
    likes = models.ManyToManyField(User, blank=True, related_name='likes')
    dislikes = models.ManyToManyField(
        User, blank=True, related_name='dislikes')

    tags = models.ManyToManyField('Tag', blank=True)

    def create_tags(self):
        for word in self.body.split():
            if (word[0] == '#'):
                tag = Tag.objects.filter(name=word[1:]).first()
                if tag:
                    self.tags.add(tag.pk)
                else:
                    tag = Tag(name=word[1:])
                    tag.save()
                    self.tags.add(tag.pk)
                self.save()

        if self.shared_body:
            for word in self.shared_body.split():
                if (word[0] == '#'):
                    tag = Tag.objects.filter(name=word[1:]).first()
                    if tag:
                        self.tags.add(tag.pk)
                    else:
                        tag = Tag(name=word[1:])
                        tag.save()
                        self.tags.add(tag.pk)
                    self.save()

    class Meta:
        ordering = ['-created_on', '-shared_on']


class Donation(models.Model):

    body = models.TextField(blank=True, null=True)
    image = models.ManyToManyField('Image', blank=True)
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.TextField(blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)


class Comment(models.Model):
    comment = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    likes = models.ManyToManyField(
        User, blank=True, related_name='comment_likes')
    dislikes = models.ManyToManyField(
        User, blank=True, related_name='comment_dislikes')
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, blank=True, null=True, related_name='+')
    tags = models.ManyToManyField('Tag', blank=True)

    def create_tags(self):
        for word in self.comment.split():
            if (word[0] == '#'):
                tag = Tag.objects.get(name=word[1:])
                if tag:
                    self.tags.add(tag.pk)
                else:
                    tag = Tag(name=word[1:])
                    tag.save()
                    self.tags.add(tag.pk)
                self.save()

    @property
    def children(self):
        return Comment.objects.filter(parent=self).order_by('-created_on').all()

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False


class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, verbose_name="user",
                                related_name='profile', on_delete=models.CASCADE)
    name = models.CharField(max_length=30, blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    picture = models.ImageField(
        upload_to='uploads/profile_pictures', default='uploads/profile_pictures/default.png')
    followers = models.ManyToManyField(
        User, blank=True, related_name='followers')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Notification(models.Model):
    # 1 = Like, 2 = Comment, 3 = Follow
    notification_type = models.IntegerField()
    to_user = models.ForeignKey(
        User, related_name='notification_to', on_delete=models.CASCADE, null=True)
    from_user = models.ForeignKey(
        User, related_name='notification_from', on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(
        'Post', on_delete=models.CASCADE, related_name='+', blank=True, null=True)
    comment = models.ForeignKey(
        'Comment', on_delete=models.CASCADE, related_name='+', blank=True, null=True)
    thread = models.ForeignKey(
        'ThreadModel', on_delete=models.CASCADE, related_name='+', blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    user_has_seen = models.BooleanField(default=False)


class ThreadModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    receiver = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='+')


class MessageModel(models.Model):
    thread = models.ForeignKey(
        'ThreadModel', related_name='+', on_delete=models.CASCADE, blank=True, null=True)
    sender_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='+')
    receiver_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='+')
    body = models.CharField(max_length=1000)
    image = models.ImageField(
        upload_to='uploads/message_photos', blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)


class Image(models.Model):
    image = models.ImageField(
        upload_to='uploads/post_photos', blank=True, null=True)


class Tag(models.Model):
    name = models.CharField(max_length=255)

volunteers/forms.py
from django import forms
from .models import Post, Comment, MessageModel


class PostForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'rows': '3',
                'placeholder': 'Say something...'
            }
        )
    )

    image = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'multiple': True
        })
    )

    class Meta:
        model = Post
        fields = ['body']

class DonationForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'rows': '3',
                'placeholder': 'Describe your donation'
            }
        )
    )

    address = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'rows': '1',
                'placeholder': 'Your address'
            }
        )
    )

    image = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'multiple': True
        })
    )

    

    class Meta:
        model = Post
        fields = ['body', 'address', 'image']



class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'rows': '3',
                'placeholder': 'Say something...'
            }
        )
    )

    class Meta:
        model = Comment
        fields = ["comment"]


class ThreadForm(forms.Form):
    username = forms.CharField(label='', max_length=100)


class MessageForm(forms.ModelForm):
    body = forms.CharField(label='', max_length=1000)

    image = forms.ImageField(required=False)

    class Meta:
        model = MessageModel
        fields = ['body', 'image']


class ShareForm(forms.Form):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
        }))


class ExploreForm(forms.Form):
    query = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={
            'placeholder': 'Explore tags'
        })
    )

volunteers/templates/volunteers/create_thread.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-md-12 p-5">
			<a href="{% url 'inbox' %}" class="btn btn-light">Back to Your Inbox</a>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12 p-5">
			<h3>Start a Conversation!</h3>
		</div>
	</div>

	<div class="row justify-content-center mt-3 mb-5">
		<div class="col-md-5 col-sm-12">
            
            {% if messages %}
            
            {% for message in messages %}
                <div class="alert alert-danger">
                    {{ message }}
                </div>
            {% endfor %}
                
            {% endif %}
                
			<form method="POST">
				{% csrf_token %}
				<p>Enter the username for the person you would like to talk to.</p>
				{{ form | crispy }}
				<div class="d-grid gap-2">
					<button class="btn btn-success mt-3" type="submit">Continue</button>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock content %}

volunteers/templates/volunteers/donation-detail.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'post-list' %}" class="btn btn-warning">Back To Feed</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <div>
                <a href="{% url 'profile' donation.author.profile.pk %}">
                    <img class="round-circle post-img" height="30" width="30"
                        src="{{ donation.author.profile.picture.url }}" />
                </a>
                <p class="post-text">
                    <a class="text-primary post-link" href="{% url 'profile' donation.author.profile.pk %}">@{{ donation.author }}</a> {{ donation.created_on }}
                    {% if post.image %}
                    <img src="{{ post.image.url }}" class="post-image h-100" />
                    {% endif %}
                </p>
            </div>
            {% if request.user == post.author %}
            <a href="{% url 'post-edit' post.pk %}" class="edit-color"><i class="fa fa-edit"></i></a>
            <a href="{% url 'post-delete' post.pk %}" class="edit-color"><i class="fa fa-trash"></i></a>
            {% endif %}
            {% if post.image.count > 0 %}
            <div class="row">
                {% for img in post.image.all %}
                <div class="col-md-4 col-xs-12">
                    <img src="{{ img.image.url }}" class="post-image" />
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <div class="body">
                <p>{{ donation.body }}</p>
                <!-- <p>{{ donation.longitude }}</p>
                <p>{{ donation.latitude }}</p> -->
                <p>{{ donation.location }}</p>

            </div>




            <div id='map' style='width: auto; height: 300px;'></div>
            <script>
                
                const long = '{{ donation.longitude }}'
                const lat = '{{ donation.latitude }}'
                // TO MAKE THE MAP APPEAR YOU MUST
                // ADD YOUR ACCESS TOKEN FROM
                // https://account.mapbox.com
                mapboxgl.accessToken = 'pk.eyJ1Ijoia2Fsa2lkYW4wOSIsImEiOiJjbDNpYno1NXgwb2R2M2NueG1zb2RhaGU4In0.gkhnMaooBBuE9qMmIxuRwQ';
                const map = new mapboxgl.Map({
                    container: 'map', // container ID
                    style: 'mapbox://styles/mapbox/streets-v11', // style URL
                    center: [long, lat], // starting position [lng, lat]
                    zoom: 9 // starting zoom
                });



                // Create a new marker.

                const marker = new mapboxgl.Marker()
                    .setLngLat([long, lat]).addTo(map);

            </script>


        </div>
    </div>



</div>

{% endblock content %}

volunteers/templates/volunteers/donation-list.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container map">
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h5>Add a Post!</h5>
        </div>
    </div>
    <div id='map' style='width: auto; height: 300px;'></div>

    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3">Submit!</button>
                </div>
            </form>
        </div>
    </div>

    {% for donation in donation_list %}
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom position-relative">
            <div>
                <a href="{% url 'profile' post.author.profile.pk %}">
                    <img class="round-circle post-img" height="30" width="30" src="{{ post.author.profile.picture.url }}" />
                </a>
                <p class="post-text">
                    <a class="text-primary post-link" href="{% url 'profile' post.author.profile.pk %}">@{{ donation.author }}</a> {{ donation.created_on }}
                </p>
            </div>

           
            <div class="shared-post position-relative pt-3">
                {% if donation.image.count > 0 %}
                  <div class="row">
                    {% for img in donation.image.all %}
                        <div class="col-md-4 col-xs-12">
                            <img src="{{ img.image.url }}" class="post-image" />
                        </div>
                    {% endfor %}
                  </div>
                {% endif %}
                <div class="body">
                    <p>{{ donation.body }}</p>
                </div>
                <a href="{% url 'post-detail' post.pk %}" class="stretched-link"></a>
            </div>
    </div>
    {% endfor %}
</div>

<script>
    mapboxgl.accessToken = 'pk.eyJ1Ijoia2Fsa2lkYW4wOSIsImEiOiJjbDNpYno1NXgwb2R2M2NueG1zb2RhaGU4In0.gkhnMaooBBuE9qMmIxuRwQ';

    const map = new mapboxgl.Map({
        container: 'map', // container id
        style: 'mapbox://styles/mapbox/satellite-v9',
        center: [-96, 37.8], // starting position
        zoom: 3 // starting zoom
    });

    // Add geolocate control to the map.
    // Initialize the geolocate control.
    const geolocate = new mapboxgl.GeolocateControl({
        positionOptions: {
            enableHighAccuracy: true
        },
        trackUserLocation: true
    });
    // Add the control to the map.
    map.addControl(geolocate);
    map.on("load", function () {
        geolocate.trigger(); // add this if you want to fire it by code instead of the button
    });
    geolocate.on("geolocate", locateUser);

    function locateUser(e) {
        console.log("A geolocate event has occurred.");
        console.log("lng:" + e.coords.longitude + ", lat:" + e.coords.latitude);
    }
</script>
{% endblock content %}

volunteers/templates/volunteers/donation.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h5>Add a Post!</h5>
        </div>
    </div>

    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3">Submit!</button>
                </div>
            </form>
        </div>
    </div>

    {% for post in post_list %}
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom position-relative">
            {% if post.shared_user %}
            <div>
                <a href="{% url 'profile' post.shared_user.profile.pk %}">
                    <img class="round-circle post-img" height="30" width="30" src="{{ post.shared_user.profile.picture.url }}" />
                </a>
                <p class="post-text">
                    <a class="text-primary post-link" href="{% url 'profile' post.shared_user.profile.pk %}">@{{ post.shared_user }}</a> shared a post on {{ post.shared_on }}
                </p>
            </div>
            {% else %}
            <div>
                <a href="{% url 'profile' post.author.profile.pk %}">
                    <img class="round-circle post-img" height="30" width="30" src="{{ post.author.profile.picture.url }}" />
                </a>
                <p class="post-text">
                    <a class="text-primary post-link" href="{% url 'profile' post.author.profile.pk %}">@{{ post.author }}</a> {{ post.created_on }}
                    <span onclick="shareToggle('{{ post.pk }}')"><i class="fa fa-share-square share-btn"></i></span>
                </p>
            </div>
            {% endif %}
            <form method="POST" action="{% url 'share-post' post.pk %}" class="d-none" id="{{ post.pk }}">
                {% csrf_token %}
                {{ shareform | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3">share the post</button>
                </div>
            </form>
            {% if post.shared_body %}
            <div class="position-relative border-bottom mb-3 body">
                <p>{{ post.shared_body }}</p>
            </div>
            <div class="shared-post">
                <a href="{% url 'profile' post.author.profile.pk %}">
                    <img class="round-circle post-img" height="30" width="30" src="{{ post.author.profile.picture.url }}" />
                </a>
                <p class="post-text">
                    <a class="text-primary post-link" href="{% url 'profile' post.author.profile.pk %}">@{{ post.author }}</a> {{ post.created_on }}
                </p>
            </div>
            {% endif %}
            <div class="shared-post position-relative pt-3">
                {% if post.image.count > 0 %}
                  <div class="row">
                    {% for img in post.image.all %}
                        <div class="col-md-4 col-xs-12">
                            <img src="{{ img.image.url }}" class="post-image" />
                        </div>
                    {% endfor %}
                  </div>
                {% endif %}
                <div class="body">
                    <p>{{ post.body }}</p>
                </div>
                <a href="{% url 'post-detail' post.pk %}" class="stretched-link"></a>
            </div>

            <div class="d-flex flex-row">
                <form method="POST" action="{% url 'like' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="fa fa-thumbs-up"> <span>{{ post.likes.all.count }}</span></i>
                    </button>
                </form>

                <form method="POST" action="{% url 'dislike' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="fa fa-thumbs-down"> <span>{{ post.dislikes.all.count }}</span></i>
                    </button>
                </form>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

volunteers/templates/volunteers/followers_list.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'profile' profile.pk %}" class="btn btn-light">Back to Profile</a>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
    	<div class="col-md-5 col-sm-12">
    		{% if profile.name %}
    		<h3>Followers for {{ profile.name }}</h3>
    		{% else %}
    		<h3>Followers for @{{ profile.user.username }}</h3>
    		{% endif %}
    	</div>
    </div>

    {% for follower in followers %}
    <div class="row justify-content-center post-link">
    	<div class="col-md-5 col-sm-12 position-relative my-3">
    		<a href="{% url 'profile' follower.profile.pk %}" class="post-link"><img class="rounded-circle post-img" height="60" width="60" src="{{ follower.profile.picture.url }}" /></a>
    		<a href="{% url 'profile' follower.profile.pk %}" class="post-link"><h5 class="mt-3">@{{ follower.username }}</h5></a>

    	</div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

volunteers/templates/volunteers/post-edit.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-3 col-sm-12">
                <a href="{% url 'post-detail' object.pk %}" class="btn btn-warning">Back To Post</a>      
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-3 col-sm-12 border-bottom">
                <h1>Update your post!</h1>
            
            </div>
        </div>

        <div class="row justify-content-center mt-3 mb-5">
            <div class="col-md-3 col-sm-12 border-bottom">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy}}
                
                <div class="d-grid gap-2">
                    <button class="btn btn-primary">Update</button>
                </div>
                </form>
            
            </div>
        </div>

            
    </div>
{% endblock content %}
    

volunteers/templates/volunteers/post-list.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h5>Add a Post!</h5>
        </div>
    </div>

    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3">Submit!</button>
                </div>
            </form>
        </div>
    </div>

    {% for post in post_list %}
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom position-relative">
            {% if post.shared_user %}
            <div>
                <a href="{% url 'profile' post.shared_user.profile.pk %}">
                    <img class="round-circle post-img" height="30" width="30" src="{{ post.shared_user.profile.picture.url }}" />
                </a>
                <p class="post-text">
                    <a class="text-primary post-link" href="{% url 'profile' post.shared_user.profile.pk %}">@{{ post.shared_user }}</a> shared a post on {{ post.shared_on }}
                </p>
            </div>
            {% else %}
            <div>
                <a href="{% url 'profile' post.author.profile.pk %}">
                    <img class="round-circle post-img" height="30" width="30" src="{{ post.author.profile.picture.url }}" />
                </a>
                <p class="post-text">
                    <a class="text-primary post-link" href="{% url 'profile' post.author.profile.pk %}">@{{ post.author }}</a> {{ post.created_on }}
                    <span onclick="shareToggle('{{ post.pk }}')"><i class="fa fa-share-square share-btn"></i></span>
                </p>
            </div>
            {% endif %}
            <form method="POST" action="{% url 'share-post' post.pk %}" class="d-none" id="{{ post.pk }}">
                {% csrf_token %}
                {{ shareform | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3">share the post</button>
                </div>
            </form>
            {% if post.shared_body %}
            <div class="position-relative border-bottom mb-3 body">
                <p>{{ post.shared_body }}</p>
            </div>
            <div class="shared-post">
                <a href="{% url 'profile' post.author.profile.pk %}">
                    <img class="round-circle post-img" height="30" width="30" src="{{ post.author.profile.picture.url }}" />
                </a>
                <p class="post-text">
                    <a class="text-primary post-link" href="{% url 'profile' post.author.profile.pk %}">@{{ post.author }}</a> {{ post.created_on }}
                </p>
            </div>
            {% endif %}
            <div class="shared-post position-relative pt-3">
                {% if post.image.count > 0 %}
                  <div class="row">
                    {% for img in post.image.all %}
                        <div class="col-md-4 col-xs-12">
                            <img src="{{ img.image.url }}" class="post-image" />
                        </div>
                    {% endfor %}
                  </div>
                {% endif %}
                <div class="body">
                    <p>{{ post.body }}</p>
                </div>
                <a href="{% url 'post-detail' post.pk %}" class="stretched-link"></a>
            </div>

            <div class="d-flex flex-row">
                <form method="POST" action="{% url 'like' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="fa fa-thumbs-up"> <span>{{ post.likes.all.count }}</span></i>
                    </button>
                </form>

                <form method="POST" action="{% url 'dislike' post.pk %}">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class="remove-default-btn" type="submit">
                        <i class="fa fa-thumbs-down"> <span>{{ post.dislikes.all.count }}</span></i>
                    </button>
                </form>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}